---
title: "Research"
---

------------------------------------------------------------------------

### Publications

1.  Zhang Y. & Yang W. 2022.Breakthrough invention and problem complexity: Evidence from a quasi-experiment. ***Strategic Management Journal,*** 43(12), 2510-2544.

2.  Polidoro F. & Yang W. 2021. Corporate investment relationships and the search for innovations: An examination of startups' search shift toward incumbents. ***Organization Science***, 32(4), 909-939.

3.  Chandler D., Polidoro F. & Yang, W. 2020. When is it good to be bad? Contrasting effects of multiple reputations for bad behavior on media coverage of serious organizational errors. ***Academy of Management Journal***, 63(4), 1236-1265.

4.  He W., Yang W. & Choi S.J., 2018. The interplay between private and public regulations: Evidence from ISO14001 adoption among Chinese firms. ***Journal of Business Ethics***, 152(2), 477-497.

5.  Hekman D., Johnson S., Foo M. & Yang W. 2017. Does diversity-valuing behavior result in diminished performance ratings for non-white and female leaders? ***Academy of Management Journal***, 60(2), 771-797.

\_\_\_\_\_

### Book chapters and refereed conference proceedings

6.  Polidoro F. & Yang W. 2019. Venture growth and multi-homing expansion: evidence from open-source platform complementors. Academy of Management Best Paper Proceedings. 

7.  Yang W. 2017. Exploring the role of venture capital in inward licensing and start-up innovation. In ***The World Scientific Reference on Entrepreneurship***, D. Siegel (Ed.). World Scientific Publishing, 307-330.

8.  Polidoro F. & Yang W. 2016. Stock market responses to firms' greening strategies in the face of climate change. ***Academy of Management Best Paper Proceedings.***

9.  Yang W. 2016. Examining the impact of government investment in venture capital on entrepreneurship financing: does it make a difference? In ***Global Entrepreneurship: Past, Present & Future***, T.M. Devinney, T. Pedersen, G.D. Markman, L. Tihanyi (Ed.). Emerald Group Publishing Limited, 235-256.

\_\_\_\_\_

### Working Papers

-   Yang W. Value of ecosystem openness. Under review at ***Management Science***.

-   Yang W. & Zhang Y. General purpose technologies, breakthroughs and invention search. Under review at ***Academy of Management Journal***.

-   Polidoro F., Chandler D. & Yang, W. Analyst rating on organizational learning. Under review at ***Strategic Management Journal***.

-   Polidoro F.& Yang, W. Complementors' expansion to multiple technology ecosystems. Preparing submission.

-   Polidoro F.& Yang, W. Stock market reactions to incumbent's adaptation strategies. Preparing submission.

-   Bermiss YS. & Yang W. Organization rankings and competitive strategies. Preparing submission.

-   Yang W. & Han S. Decentralized organization design and external imprinting. Working paper.
